# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [130]:
import pandas as pd

df = pd.read_csv("Data/Purchase_Data.csv")

In [131]:
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [132]:
df.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [133]:
result_1 = df.loc[: , ["invoice_number" , "invoice_time"]]
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [134]:
result_2 = df.loc[:1]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [135]:
result_3 = df.loc[:3 , df.columns[:5]]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [136]:
result_4 = df.loc[[0,4,6] , ["invoice_time" , "price"]]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [137]:
num_rows = len(df)
num_rows

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [138]:
df.iloc[num_rows - 1]

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [139]:
avg_price = df["price"].mean()
avg_price

3.1920522110741363

In [140]:
max_price = df["price"].max()
max_price

6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [141]:
avg_price = df["price"].mean()
avg_price

3.1920522110741363

In [142]:
avg_item = df["num_item"].mean()
avg_item

1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [143]:
df["total"] = df["price"] * df["num_item"]
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0

What is the avgerage price of the three most expensive purchases?

In [144]:
df["price"].nlargest(3).mean()

6.003333333333333

How many different products are there?

In [145]:
df["product_id"].nunique()

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [146]:
mean = df["total"].mean()
mean

3.931807878112784

In [147]:
median = df["total"].median()
median

3.0

Use the drop() method to delete the column total from the dataframe df_data.

In [148]:
df = df.drop(columns="total")
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Let's dig a little deeper into the data set and answer some basic question.

###### OK

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [149]:
pd.to_datetime(df["invoice_time"])

C:\Users\CM\AppData\Local\Temp\ipykernel_6468\3630438027.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df["invoice_time"])

0      2015-07-15 10:45:00
1      2015-07-15 12:16:00
2      2015-07-15 12:16:00
3      2015-07-15 12:16:00
4      2015-07-15 12:16:00
               ...
5377   2015-09-05 23:07:00
5378   2015-09-05 23:23:00
5379   2015-09-05 23:24:00
5380   2015-09-05 23:32:00
5381   2015-09-05 23:38:00
Name: invoice_time, Length: 5382, dtype: datetime64[ns]

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [150]:
df["invoice_time"] = pd.to_datetime(df["invoice_time"])

df["dow"] = df["invoice_time"].dt.weekday

C:\Users\CM\AppData\Local\Temp\ipykernel_6468\248918285.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["invoice_time"] = pd.to_datetime(df["invoice_time"])

In [151]:
df["month"] = df["invoice_time"].dt.month

In [152]:
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,dow,month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,2,7
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2,7
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,2,7
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,2,7
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,2,7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [153]:
# Wednesday -> 2

num_purchase_wed = df["dow"].value_counts()[2]
num_purchase_wed

959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [154]:
df = pd.read_csv("Data/Titanic.csv")

df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [155]:
df.rename(columns={"Name" : "Passenger_Name"})

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Change the index of the df_titanic to the column PasengerID.

In [156]:
df.set_index("PassengerId" , inplace= True)
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Select the name of passenger 896

In [157]:
df.loc[896 , "Name"]

'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [158]:
df.reset_index(inplace= True)
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [164]:
df["Age"].isnull().count()

418

Compute the avg age of passengers ignoring the missing data.

In [165]:
df["Age"].mean()

30.272590361445783

Using the fillna() method replace the missing values in the Age column with the mean.

In [166]:
df["Age"].fillna(df["Age"].mean())

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [167]:
df["Age"].nlargest(5).mean()

67.0